config {
  type: 'view',
  description: '!!! Mocking Staging for orders_lavka',
  schema: 'staging',
  tags: ['lavka', 'staging', 'push_performance', 'view'],
  name:'stg_lavka__orders_lavka',
  assertions: {
    nonNull: ['id', 'preorder_id', 'price'],
    uniqueKey: ['id', 'preorder_id']
  }
}

select
    id,
    preorder_id,
    price
from
    ${ref('orders_lavka')}
where
    date(created_at) > '2025-08-01'